version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - test-3.7
      - test-3.8
      - test-3.9
      - test-3.10
      - static-code-analysis

defaults: &defaults
  working_directory: ~/code
  steps:
  - checkout
  - run:
      name: Install Python dependencies
      command: CFLAGS="-O0" pip install -r requirements_tests.txt
  - run:
      name: Test
      command: pytest

jobs:
  test-3.7:
    <<: *defaults
    docker:
    - image: cimg/python:3.7
  test-3.8:
    <<: *defaults
    docker:
    - image: cimg/python:3.8
  test-3.9:
    <<: *defaults
    docker:
      - image: cimg/python:3.9
  test-3.10:
    <<: *defaults
    docker:
      - image: cimg/python:3.10
  static-code-analysis:
    working_directory: ~/code
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install lintlizard==0.18.0 "click<8.1"
      - run:
          name: LintLizard
          command: lintlizard
